config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users 
  resources :categories 

  # resources :users do
  #   resources :products do
  #     member do
  #       get :add_to_cart
  #     end
  #   end
  # end

  resources :users do
    resources :products do
     # member do
     #   get :add_to_cart
     # end
    end

    resources :suppliers 
    resources :carts do
      resources :cartships
      member do
        get :add_to_cartship
        post :pay
        post :remove_item
      end
    end
  end

# resources :users do
#   resources :suppliers 
# end


  

  get 'sales/index'

  #root to: redirect('/users/sign_in')

  root 'sales#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :cartships, dependent: :destroy
  has_many :products, through: :cartships

  def total_price
    cartships.map { |cartship| cartship.quantity * cartship.product.price }.sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart, only: [:show, :edit, :update, :destroy, :pay]

  # GET /carts
  # GET /carts.json
  def index
    @carts = current_user.carts.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    Cart.create! user_id: current_user.id, status: "pending"    
    redirect_to new_user_cart_cartship_path(user_id: current_user.id, cart_id: Cart.first.id, product_id: params[:product_id])
  end


  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = current_user.carts.new(cart_params)

    respond_to do |format|
      if @cart.save
        
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to sales_index_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pay

    @cart.cartships.each do |cartship| 
      new_total = cartship.product.quantity - cartship.quantity
      cartship.product.update! quantity: new_total
    end

    @cart.destroy
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = current_user.carts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:status, :user_id, :product_id)
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%#= form_with(model: cart, local: true) do |form| %>
<%= simple_form_for([@current_user, @cart]) do |form| %>


    <%= form.input :status %>
    <%= form.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }%>
  

  
    <%= form.submit %>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td>
          <%#= link_to cart.status, user_cart_path(current_user, cart) %>
          <%= link_to cart.status, user_cart_path(current_user, cart) %>
        </td>
        <td><%= link_to 'Sil', user_cart_path(current_user, cart), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', user_carts_path(current_user) %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <h2>Sepet</h2>
    <tr>
      <th>ürün</th>
      <th>adet</th>
      <th>birim fiyatı</th>
      <th>toplam fiyatı</th>
      <th><%#= button_to 'Sepeti Sil', @cart, method: :delete, data: { confirm: 'Sepeti Silmekten Emin Misiniz?' }, class: 'clear button alert' %></th>
      <th>
        <%#= button_to 'Sepeti Sil', user_cart_path(current_user, cart) method: :delete, data: { confirm: 'Sepeti Silmekten Emin Misiniz?' }, class: 'clear button alert' %>
          
        </th>
        <th>
          <th><%#= button_to 'Sepeti Sil', user_cart_url, method: :delete, data: { confirm: 'Sepeti Silmekten Emin Misiniz?' }, class: 'clear button alert' %></th>
      <th>
        </th>
      <%= button_to 'satışı tamamla', pay_user_cart_path(current_user) %>
      <th colspan="4"></th>

    </tr>
  </thead>

  <tbody>
    <% @cart.cartships.each do |cartship| %>
      <tr>
        <td>
          <%= cartship.product.title %>
        </td>
        <td>
          <%= cartship.quantity %>
        </td>
        <td>
          <%= cartship.product.price %>
        </td>
        <td>
          <%= cartship.product.price * cartship.quantity %>          
        </td>
        <td>
          <%= button_to 'sepetten çıkar', user_cart_cartship_path(current_user, @cart, cartship), method: :delete, data: { confirm: 'Ürün Sepetten Çıkarılıyor' }, class: 'clear button alert' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<h6 class="subheader">
  <%=  " Toplam #{@cart.total_price} ₺"   %>
</h6>