config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users 
  resources :categories 

  # resources :users do
  #   resources :products do
  #     member do
  #       get :add_to_cart
  #     end
  #   end
  # end

  resources :users do
    resources :products do
     # member do
     #   get :add_to_cart
     # end
    end

    resources :suppliers 
    resources :carts do
      resources :cartships
      member do
        get :add_to_cartship
        post :pay
        post :remove_item
      end
    end
  end

# resources :users do
#   resources :suppliers 
# end


  

  get 'sales/index'

  #root to: redirect('/users/sign_in')

  root 'sales#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :supplier
  belongs_to :user
  validates :title, presence: true
  validates :price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy, :add_to_cart]
  
  # GET /products
  # GET /products.json
  def index
    #@products = Product.order(:title).to_a
    #@products = current_user.products.order(:title).to_a
    @products = current_user.products.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @user = User.all
    @product = Product.new
    @category = Category.all
    @supplier = Supplier.all
  end

  # GET /products/1/edit
  def edit
    
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        # format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.html { redirect_to user_products_url, notice: 'Ürün Eklendi.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Ürün Güncellendi' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Ürün Silindi.' }
      format.json { head :no_content }
    end
  end

   

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      @category = Category.find(params[:id])
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :category_id, :supplier_id, :quantity, :user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%#= simple_form_for(@product) do |f| %>
<%= simple_form_for(@product, url: user_products_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    
    <%= f.input :title, label: "Ürün Adı" %>
    <%= f.input :price, label: "Birim Fiyatı" %>
    <%= f.association :category, label: "Kategori" %>
    <%= f.association :supplier, label: "Tedarikçi"  %>
    <%= f.input :quantity, label: "Adet" %>
    <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }%>
  </div>

  <div class="form-actions">
  

  
    <%= f.button :submit, "Ekle", class: 'button success' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Ürün Güncelleme </h1>

<%= render 'form', product: @product %>

<%= link_to 'Görüntüle', @product %> |
<%= link_to 'Geri', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ürün Listesi</h1>

<table>
  <thead>
    <tr>
      <th>Ürün Adı</th>
      <th>Birim Fiyatı</th>
      <th>Kategori</th>
      <th>Tedarikçi</th>
      <th>Stok Sayısı</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= link_to product.title, user_product_path(current_user, product) %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= product.category.title %>
        </td>
        <td>
          <%= product.supplier.name %>
        </td>
        <td>
          <%= product.quantity %>
        </td>
        <!-- <td> -->
          
          <%#= link_to 'Add to Cart', add_to_cart_product_path(product)  %>
          
        <!-- </td> -->

        <td><%= link_to 'Güncelle', edit_user_product_path(current_user, product), class: 'clear button' %></td>
        <td><%= link_to 'Ürünü Sil', user_product_path(current_user, product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'clear button alert' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Yeni Ürün Ekle', new_user_product_path(current_user), class: 'button success' %>

app/views/products/new.html.erb
<h1>Yeni Ürün</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Güncelle', edit_product_path(@product) %> |
<%= link_to 'Geri', products_path %>