config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users 
  resources :categories 

  # resources :users do
  #   resources :products do
  #     member do
  #       get :add_to_cart
  #     end
  #   end
  # end

  resources :users do
    resources :products do
     # member do
     #   get :add_to_cart
     # end
    end

    resources :suppliers 
    resources :carts do
      resources :cartships
      member do
        get :add_to_cartship
        post :pay
        post :remove_item
      end
    end
  end

# resources :users do
#   resources :suppliers 
# end


  

  get 'sales/index'

  #root to: redirect('/users/sign_in')

  root 'sales#index'
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :user
  has_many :products
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  # GET /suppliers
  # GET /suppliers.json
  def index
    #@suppliers = current_user.suppliers.all
    #@suppliers = supplier.order(:name).to_a
    @suppliers = current_user.suppliers.all

  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to user_suppliers_url, notice: 'Supplier was successfully created.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
      @current_user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:name, :phone, :address, :user_id)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= simple_form_for(@supplier, url: user_suppliers_path) do |f| %>
<%#= simple_form_for(@supplier) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: "Firma Adı"%>
    <%= f.input :phone, label: "Telefon" %>
    <%= f.input :address, label: "Adres" %>
    <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Ekle", class: 'button success' %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Tedarikçi Güncelleme</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tedarikçiler Listesi</h1>

<table>
  <thead>
    <tr>
      <th>Firma Adı</th>
      <th>Telefon</th>
      <th>Adres</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.name %></td>
        <td><%= supplier.phone %></td>
        <td><%= supplier.address %></td>
        <td><%= link_to 'Güncelle', edit_user_supplier_path(current_user, supplier), class: 'clear button' %></td>
        <td><%= link_to 'Sil', user_supplier_path(current_user, supplier), method: :delete, data: { confirm: '1 Tedarikçi Silinecek.' }, class: 'clear button alert' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Yeni Tedarikçi', new_user_supplier_path(current_user), class: 'button success'%>

app/views/suppliers/new.html.erb
<h1>Yeni Tedarikçi</h1>

<%= render 'form', supplier: @supplier %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @supplier.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @supplier.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @supplier.address %>
</p>

<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>