config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users 
  resources :categories 

  # resources :users do
  #   resources :products do
  #     member do
  #       get :add_to_cart
  #     end
  #   end
  # end

  resources :users do
    resources :products do
     # member do
     #   get :add_to_cart
     # end
    end

    resources :suppliers 
    resources :carts do
      resources :cartships
      member do
        get :add_to_cartship
        post :pay
        post :remove_item
      end
    end
  end

# resources :users do
#   resources :suppliers 
# end


  

  get 'sales/index'

  #root to: redirect('/users/sign_in')

  root 'sales#index'
end

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <div class="top-bar">
    <div class="top-bar-left">
      <ul class="menu">
        <li>
        <%= link_to 'Ana Sayfa', root_path %>
        </li>
        <li>
          <ul class="dropdown menu" data-dropdown-menu>
            <li>
              <a>Ürün</a>
              <ul class="menu">
                <li><%#= link_to 'Ürünleri Listele', products_path %></li>
                <li><%= link_to 'Ürünleri Listele', user_products_path(current_user) %></li>
                <li><%#= link_to 'Ürün Ekle', new_product_path %></li>
                <li><%= link_to 'Ürün Ekle', new_user_product_path(current_user) %></li>
              </ul>
            </li>
            <li>
              <a>Kategori</a>
              <ul class="menu">
                <%= link_to 'Kategorileri Listele', categories_path %>
                <%= link_to 'Kategori Ekle', new_category_path %>
              </ul>
            </li>
            <li>
              <a>Tedarikçi</a>
              <ul class="menu">
                <%= link_to 'Tedarikçileri Listele', user_suppliers_path(current_user) %>
            </li>
                <%= link_to 'Tedarikçi Ekle', new_user_supplier_path(current_user) %>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li>
          <li>
            <%#= link_to "Sepet (#{Cart.first.cartships.count})", user_carts_path(Cart.first) if Cart.any? %>
            <%#= link_to "Sepet (#{@cart.cartships.count})", user_cart_path(current_user, @cart, @cartship) if Cart.any? %>
          </li>
          <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          
        </li>
      </ul>
    </div>

  </div>

<% else %> 

<div class="top-bar">
  <div class="top-bar-right">
    <ul class="menu">
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    </ul>
  </div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation'  %>
    <%= yield %>

  </body>
</html>